name: Test Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore ./src/BetterEnums/YACL.BetterEnums.Abstractions/YACL.BetterEnums.Abstractions.csproj

      - name: Build
        run: dotnet build ./src/BetterEnums/YACL.BetterEnums.Abstractions/YACL.BetterEnums.Abstractions.csproj -c Release --no-restore

      - name: Pack
        run: |
          dotnet pack ./src/BetterEnums/YACL.BetterEnums.Abstractions/YACL.BetterEnums.Abstractions.csproj \
            -c Release \
            --no-build \
            -o ./nugets

      - name: Push
        run: |
          dotnet nuget push "./nugets/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
